pyproject.toml
- Add framework source code
- Documentation build
- Readme
=> Version 0.0.3

council/skills/llm_skill.py
Updating docstring in `LLMSkill` class.
=> Updating LLMSkill docstring

README.md, docs/source/introduction/key_features.md, docs/source/introduction/welcome.md
add LlamaIndex integration to welcome
=> Update welcome.md - add LlamaIndex

README.md, docs/source/conf.py, docs/source/introduction/welcome.md
Resolve #56 by updating the discord link to the proper endpoint.
=> Fix README discord link (#56)

pyproject.toml
=> Release 0.0.9

council/runners/if_runner.py, tests/unit/runners/test_if.py, tests/unit/runners/test_parallel_for.py
- fix missing monitor dependencies on `IfRunner`
- add an optional `else_runner`
=> Feature fix if runner missing monitor dependency and add an else runner

pyproject.toml
- export type hints for `mypy`
=> Feature exporting type hints

council/__init__.py
implementation for issue/feature request: https://github.com/chain-ml/council/issues/100
=> Add commonly used types in council main module

council/contexts/_execution_log_entry.py, council/skills/wikipedia/wikipedia_client.py, tests/unit/contexts/test_agent_context.py
=> CU-8686yqa3h_Fix-execute_log_to_json-when-a-log-entry-contains-an-error

README.md
- Delete Roadmap section from README.md
=> Suppress roadmap section until further notice

council/llm/openai_token_counter.py, dev-requirements.txt, requirements.txt, tests/unit/llm/test_openai_token_counter.py
=> Feature support new openai models 20240607

pyproject.toml
=> Release 0.0.18

council/llm/__init__.py, council/llm/llm_function.py, council/llm/llm_middleware.py, tests/integration/llm/test_llm_function.py
- Add list of messages to the exec function
- Change Response parser from str to LLMResponse
=> Enhance LLMFunction

council/llm/llm_message.py
- Add a method to add LLMMessageData
- Add [LLMMessageData] to constructor
=> Enhance LLMMessage class

council/llm/llm_message.py, council/llm/openai_chat_gpt_configuration.py, council/utils/__init__.py, council/utils/parameter.py
- Support OpenAI's fine-tuned models with `prefix_any_validator`
- Add `format()` and `__str__()` for `LLMMessage`
=> Feature support fine-tuned models

council/llm/llm_function.py, tests/integration/llm/test_llm_function.py, tests/unit/llm/test_code_blocks_response_parser.py
- Implement `code_blocks_response_parser` to automatically parse `LLMResponse` code blocks content into class fields
=> Feature code_blocks_response_parser

council/llm/llm_function_with_prompt.py, tests/data/prompt-sql.yaml, tests/data/prompt-template-sql.yaml, tests/integration/llm/test_llm_function.py, tests/integration/llm/test_llm_function_with_prompt.py, tests/unit/__init__.py
- Implement `LLMFunctionWithPrompt` - `LLMFunction` configured with `LLMPrompt`
=> Feature LLMFunctionWithPrompt

council/utils/code_parser.py, tests/unit/utils/test_code_parser.py
PR includes:
- updating `CodeParser._get_pattern` to match languages containing special characters such as `c++`
- adding unit test in `test_code_parser.py`
=> Update code parser pattern to handle languages with special characters

council/llm/llm_function.py, council/llm/llm_response_parser.py, docs/source/reference/llm/llm_response_parser.rst, tests/integration/llm/test_llm_function.py, tests/unit/llm/test_llm_response_parser_blocks.py
- Support `LLMMessage` input for `LLMFunction.__init__()`
- Introduce `EchoResponseParser` and `StringResponseParser`
=> Feature LLMMessage for LLMFunction

council/llm/llm_function_with_prompt.py, tests/data/prompt-abc.yaml, tests/data/prompt-large.yaml, tests/data/prompt-sql.yaml, tests/data/prompt-template-sql.yaml, tests/integration/llm/test_llm_function_with_prompt.py, tests/unit/__init__.py
- Implement opportunity to cache entire system prompt for `LLMFunctionWithPrompt`
=> Feature prompt caching for LLMFunctionWithPrompt

council/llm/llm_function.py, council/mocks/mock_llm.py, requirements.txt, tests/unit/llm/test_llm_consumption_calculators.py
Implement proper consumptions management for `LLMFunction` self-correction - now `LLMFunctionResponse` contains consumptions not only for final result, but for intermediate attempts as well
=> Feature consumptions for self-correction

council/llm/data/anthropic-costs.yaml, tests/integration/llm/test_anthropic_llm.py, tests/unit/llm/test_llm_consumption_calculators.py
Support cost calculations for `claude-3-5-haiku-20241022`
=> Feature support claude-3.5-haiku

council/llm/__init__.py, council/llm/anthropic_llm_configuration.py, council/llm/chat_gpt_configuration.py, council/llm/gemini_llm_configuration.py, council/llm/llm_config_object.py, council/llm/ollama_llm.py, council/llm/ollama_llm_configuration.py, council/llm/openai_chat_completions_llm.py, council/utils/__init__.py, council/utils/parameter.py, docs/data/configs/llm-config-ollama.yaml, docs/source/reference/llm.md, docs/source/reference/llm/llm_config_object.md, docs/source/reference/llm/ollama_llm.md, docs/source/reference/llm/ollama_llm_configuration.md, requirements.txt, tests/data/ollama-llmodel.yaml, tests/integration/llm/test_ollama_llm.py, tests/unit/__init__.py, tests/unit/llm/test_llm_config_object.py, tests/unit/llm/test_ollama_llm_configuration.py
- Implement `OllamaLLM` and `OllamaLLMConfiguration`
- Manage consumptions for local models based on response metadata provided
- Update docs
- Minor refactoring
=> Initial ollama implementation

council/llm/__init__.py, council/llm/llm_middleware.py, docs/source/reference/llm/llm_middleware.md
Unify `LLMLoggingMiddleware` and `LLMFileLoggingMiddleware` format by introducing `LLMLoggingMiddlewareBase` and `LLMLoggingStrategy`
=> Feature refactor logging middlewares

council/llm/providers/gemini/data/gemini-costs.yaml, tests/integration/llm/test_gemini_llm.py, tests/unit/llm/test_llm_consumption_calculators.py
- Support new `gemini-2.0-flash-exp` model with [zero cost](https://cloud.google.com/vertex-ai/generative-ai/docs/gemini-v2#pricing)
- Add unit test to ensure all costs in yaml are floats
=> Feature support gemini-2.0-flash-exp

council/llm/llm_message.py, council/prompt/__init__.py, council/prompt/llm_dataset.py, docs/source/reference/llm/llm_dataset.md
Delete `LLMDatasetMessage` in favour of  `LLMMessage` with limited `from_dict()` and `to_dict()`
=> Feature refactor LLMDatasetMessage

council/llm/providers/anthropic/anthropic_llm_configuration.py, council/llm/providers/gemini/gemini_llm_configuration.py, council/llm/providers/groq/groq_llm_configuration.py, council/llm/providers/ollama/ollama_llm_configuration.py, council/llm/providers/openai/azure_chat_gpt_configuration.py, council/llm/providers/openai/openai_chat_gpt_configuration.py, council/skills/google/google_context/google_search.py, council/utils/__init__.py, council/utils/code_parser.py, council/utils/env.py, docs/source/reference/utils/code_parser.md, docs/source/reference/utils/env.md, tests/unit/utils/test_env.py
Implement `must_read_env_{type}()` and add docs
=> Feature must_read_env_str

council/llm/data/response_hints.yaml, council/llm/llm_response_parser.py, tests/unit/llm/test_llm_response_parser_response_template.py
- Implement `CodeBlocksResponseParser.to_response_template()` and add tests
- Refactor response hints
=> Feature CodeBlocksResponseParser.to_response_template()

council/llm/base/llm_base.py, council/llm/base/llm_message.py, council/llm/llm_function/llm_function.py, council/llm/llm_function/llm_middleware.py, council/prompt/llm_dataset.py, tests/integration/llm/test_llm_function.py
- Make `LLMResult.result()` return `LLMResult`, keep `maybe_result` for `Optional[LLMResult]`
- Add `LLMDatasetConversation.from_llm_response()`
- Minor clean-up
=> Feature refactor llm response

council/llm/__init__.py, council/llm/llm_function/__init__.py, council/llm/llm_function/llm_middleware.py, docs/source/reference/llm/llm_middleware.md, tests/unit/llm/test_llm_middleware.py
- Implement `LLMTimestampFileLoggingMiddleware` to create a separate log file for each request
=> Feature LLMTimestampFileLoggingMiddleware

council/llm/llm_function/llm_function_with_prompt.py, council/prompt/__init__.py, council/prompt/llm_prompt_config_object.py, docs/data/prompts/llm-prompt-sql-template-structured.yaml, docs/source/reference/llm/llm_prompt_config.md, tests/data/prompt-abc-structured.yaml, tests/data/prompt-template-sql-structured.yaml, tests/integration/llm/test_llm_function_with_prompt.py, tests/unit/__init__.py, tests/unit/prompt/test_llm_prompt_config.py
Initial implementation of `LLMStructuredPromptConfigObject` with ability to format `sections` with any `PromptFormatter` - `MarkdownPromptFormatter`, `XMLPromptFormatter`, etc.
=> Feature LLMStructuredPrompt
